### ISSUE TITLE
Fields in registry

### ISSUE THREAD

**Issue by tschilicous** [patroqueeet/aktienregister#1]
copy&paste gafi 
* Vor- und den Nachnamen oder die Firma 
* Adresse der Inhaberaktionäre und der wirtschaftlich berechtigten Personen.
* die Staatsangehörigkeit und das Geburtsdatum der Inhaberaktionäre

vgl
https://www.admin.ch/opc/de/federal-gazette/2014/9689.pdf
Bundesgesetz
zur Umsetzung der 2012 revidierten Empfehlungen
der Groupe d’action financière / S.9691
Obligationenrecht Art. 6971 

dazu reicht jedoch im print/ausdruck bei weiterleitung des registers folgendes:
(dh im public view sichtbar)

Bucheffektengesetz vom 3. Oktober 2008

a. Vor- und Nachname oder Firma sowie Adresse der Aktionärin oder des
Aktionärs; und
b. Vor- und Nachname sowie Adresse der wirtschaftlich berechtigten Person. 

vgl https://www.admin.ch/opc/de/federal-gazette/2014/9689.pdf
S 9705

**Comment by patroqueeet** [comment]
ok, means we will 
* assign each user to a potential company which he might(!) represent.
* collect the address of the bearer share owners or of the proxy person
* collect the country and birth date of that person

**Comment by patroqueeet** [comment]
562edc9 created base models

**Comment by patroqueeet** [comment]
3f5b48f672d6c4b4bcb6f8e79890a24a4c3f658a fixed a broken test for adding shareholder/user

**Comment by patroqueeet** [comment]
adjusting specs:
* make gafi fields optional
* introduce validation for switzerland based companies for GAFI
* mark invalid entries in captable and shareholder detail view
* make them easily editable
* requires company can setup its address/register country

**Comment by patroqueeet** [comment]
done for now.
