### ISSUE TITLE
Liste der Optionen / Begünstigten

### ISSUE THREAD

**Issue by tschilicous** [patroqueeet/aktienregister#2]
vgl Kollektivanlagengesetz

Art. 46 Abs. 3 zweiter Satz
3 … Sie führt zudem nach Artikel 697l des Obligationenrechts19 ein Verzeichnis der
Personen, die an den Aktien der Unternehmeraktionärinnen und -aktionären wirtschaftlich
berechtigt sind. 

https://www.admin.ch/opc/de/federal-gazette/2014/9689.pdf
S.9696

**Comment by patroqueeet** [comment]
all required data now included.
