### ISSUE TITLE
Option Plan

### ISSUE THREAD

**Issue by mathiasbrenner** [patroqueeet/aktienregister#30]
In order to grant Options in ticket #29 the admin need to be able to create the underlying option plan.
Informations to be filed:
- Approval Date of the Option Plan
- A title of the Option Plan
- Underlying shares/ security
- Allocation of the shares
- Comment and or uploading the pdf- option plan

**Comment by patroqueeet** [comment]
hey, what exactly do you expect from:
*allocation? how would it work?
* pdf option plan upload: this will be the pdf copy of the option plan approved by the board?

**Comment by mathiasbrenner** [comment]
- pdf option plan upload: this will be the pdf copy of the option plan approved by the board?
=> yes, exactly. 
- allocation
I'd like to store the amount of options/shares allocated per round. In other words, these are the amount of shares reserved for the option holders.

**Comment by patroqueeet** [comment]
all done. upload still missing. extra tix for that: #31
