### ISSUE TITLE
Add multiuser- support

### ISSUE THREAD

**Issue by mathiasbrenner** [patroqueeet/aktienregister#35]
No user roles needed, at least multi-login to be able to work on the same data.

**Comment by patroqueeet** [comment]
Preview: <img width="1015" alt="screenshot 2016-01-17 21 02 43" src="https://cloud.githubusercontent.com/assets/2073086/12379955/b5ba2798-bd5d-11e5-9d6f-9346dd3e47d6.png">

**Comment by patroqueeet** [comment]
done: 
![darg_ops](https://cloud.githubusercontent.com/assets/2073086/12447105/e8c6dd48-bf65-11e5-9fdb-d19241a12572.gif)

test missing

**Comment by patroqueeet** [comment]
all done with 6b9fced4fa3aa8bab7e37ab7255725e09717c0ac
