### ISSUE TITLE
Make shareholder details editable

### ISSUE THREAD

**Issue by mathiasbrenner** [patroqueeet/aktienregister#36]
http://app.das-aktienregister.ch/shareholder/20/

**Comment by mathiasbrenner** [comment]
- CRUD for Shareholder- Details

**Comment by patroqueeet** [comment]
![darg_edit_shareholder](https://cloud.githubusercontent.com/assets/2073086/12466252/0543ba4e-bfcb-11e5-8475-9b6c5a7ea76b.gif)


preview :)

**Comment by patroqueeet** [comment]
@mathias: crud: also delete?

**Comment by mathiasbrenner** [comment]
@patroqueeet yes, I'd say soft-delete. But the usecase is e.g. a wrongly added shareholder.

**Comment by patroqueeet** [comment]
then still soft delete would do the trick. means hide him from regular usage. its more consequent and trustworthy.
