### ISSUE TITLE
Add support to split shares

### ISSUE THREAD

**Issue by mathiasbrenner** [patroqueeet/aktienregister#37]

**Comment by patroqueeet** [comment]
question: split all shares at once? or is this per preferred/common stock? do have options to be adjusted? how should the split be recorded?

**Comment by patroqueeet** [comment]
[![Aktienregister Transactions Demo](http://img.youtube.com/vi/p2DXOO8a6d8/0.jpg)](http://www.youtube.com/watch?v=p2DXOO8a6d8)
